baseURL = "https://Curry-ZCR.gitihub.io"
title = "My Hugo Site"
theme = "reimu"

defaultContentLanguage = "zh-CN"
languageCode = "zh-CN"

[languages]

[languages.zh-CN]
languageName = "简体中文"
weight = 1
hasCJKLanguage = true
